server:
  port: 8086
spring:
  #?????????????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthy?useUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:

  mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: cn.zcbigdata.mybits_demo.entity

  #showSql
  logging:
    level:
      com:
        example:
          mapper: debug


